### ISSUE TITLE
Could not start after upgrade to 14 (daily)

### ISSUE THREAD

**Issue by benyanke** [benyanke/docker-nextcloud#19]
When taking an install based on 'latest', and switching to 'nightly' (simulating an upgrade from 13 -> 14), the following error occurs.

Needs to be debugged.
```
nextcloud_1  | Not updating permissions since $PERMISSION_RESET was not '1'
nextcloud_1  | Cannot write into "config" directory
nextcloud_1  | This can usually be fixed by giving the webserver write access to the config directory. See https://docs.nextcloud.com/server/13/go.php?to=admin-dir_permissions
nextcloud_1  | 
nextcloud_1  | An unhandled exception has been thrown:
nextcloud_1  | Exception: Environment not properly prepared. in /nextcloud/lib/private/Console/Application.php:148
nextcloud_1  | Stack trace:
nextcloud_1  | #0 /nextcloud/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud_1  | #1 /nextcloud/occ(11): require_once('/nextcloud/cons...')
nextcloud_1  | s6-svscan: fatal: unable to mkfifo .s6-svscan/control: Permission denied
nextcloud_1  | #2 {main}Not updating permissions since $PERMISSION_RESET was not '1'
nextcloud_1  | Cannot write into "config" directory
nextcloud_1  | This can usually be fixed by giving the webserver write access to the config directory. See https://docs.nextcloud.com/server/13/go.php?to=admin-dir_permissions
nextcloud_1  | 
nextcloud_1  | An unhandled exception has been thrown:
nextcloud_1  | Exception: Environment not properly prepared. in /nextcloud/lib/private/Console/Application.php:148
nextcloud_1  | Stack trace:
nextcloud_1  | #0 /nextcloud/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud_1  | #1 /nextcloud/occ(11): require_once('/nextcloud/cons...')
nextcloud_1  | s6-svscan: fatal: unable to mkfifo .s6-svscan/control: Permission denied
nextcloud_1  | #2 {main}Not updating permissions since $PERMISSION_RESET was not '1'
nextcloud_1  | Cannot write into "config" directory
nextcloud_1  | This can usually be fixed by giving the webserver write access to the config directory. See https://docs.nextcloud.com/server/13/go.php?to=admin-dir_permissions
nextcloud_1  | 
nextcloud_1  | An unhandled exception has been thrown:
nextcloud_1  | Exception: Environment not properly prepared. in /nextcloud/lib/private/Console/Application.php:148
nextcloud_1  | Stack trace:
nextcloud_1  | #0 /nextcloud/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud_1  | #1 /nextcloud/occ(11): require_once('/nextcloud/cons...')
nextcloud_1  | s6-svscan: fatal: unable to mkfifo .s6-svscan/control: Permission denied
nextcloud_1  | #2 {main}Not updating permissions since $PERMISSION_RESET was not '1'
nextcloud_1  | Cannot write into "config" directory
nextcloud_1  | This can usually be fixed by giving the webserver write access to the config directory. See https://docs.nextcloud.com/server/13/go.php?to=admin-dir_permissions
nextcloud_1  | 
nextcloud_1  | An unhandled exception has been thrown:
nextcloud_1  | Exception: Environment not properly prepared. in /nextcloud/lib/private/Console/Application.php:148
nextcloud_1  | Stack trace:
nextcloud_1  | #0 /nextcloud/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud_1  | #1 /nextcloud/occ(11): require_once('/nextcloud/cons...')
nextcloud_1  | s6-svscan: fatal: unable to mkfifo .s6-svscan/control: Permission denied
nextcloud_1  | #2 {main}Not updating permissions since $PERMISSION_RESET was not '1'
nextcloud_nextcloud_1 exited with code 111
```

**Comment by benyanke** [comment]
This was an unrelated issue.
